FORMAT: 1A
HOST: https://localhost:6000/

# covidSupport

CovidSupport is a simple API that can be used to add Providers and Plasma donors details and retrieve them based on certain filter also have a chat support

## PlasmaDonors [/plasma]

### List All Plasma Donors [GET]

This endpoint can be either called directly which will make it list all plasma donors or /id could be appended ion the url which will return the donor with that id.
"name", "state", "pincode", "district" can be added in the request body which will filter the results accordingly

+ Response 200 (application/json)

        [
            {
                "_id": "60863562dc7788cacc4af270",
                "Name": "Aayush",
                "State": "WB",
                "District": "Jalpaiguri",
                "Pincode": "735101",
                "Contact": "9931837670",
                "Email": "roy.a2yush@gmail.com",
                "PerWeek": 1,
                "createdAt": "2021-04-26T03:37:06.181Z",
                "__v": 0
            }
        ]

### Create a new Plasma Donor [POST]

People who wanmt to donate their plasma and have all the criterias for being a plasma donor can regiter themselves as a plasma donor 

+ Request (application/json)

        {
            "Name": "Aayush",
            "State": "WB",
            "District": "Jalpaiguri",
            "Pincode": "735101",
            "Contact": "9931837670",
            "Email": "roy.a2yush@gmail.com",
            "PerWeek": 1
        }

+ Response 201 (application/json)


    + Body

            {
                "_id": "60863562dc7788cacc4af270",
                "Name": "Aayush",
                "State": "WB",
                "District": "Jalpaiguri",
                "Pincode": "735101",
                "Contact": "9931837670",
                "Email": "roy.a2yush@gmail.com",
                "PerWeek": 1,
                "createdAt": "2021-04-26T03:37:06.181Z",
                "__v": 0
            }